language: r
sudo: required
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
r_packages:
- covr
after_success:
- Rscript -e "covr::codecov()"
